### ISSUE TITLE
text input inside the modal

### ISSUE THREAD

**Issue by slopesweb** [k-ivan/glory-modal#39]
I put a text type input inside the modal, but when I click inside the input, the modal closes. How to prevent this?

**Comment by k-ivan** [comment]
Could you make a small demo like on [codepen](https://codepen.io/)  or [codesandbox](https://codesandbox.io) or the markup of your modal window and the code associated with it. I use these modals with a lot of forms and have not experienced this behavior.
Your example would be very helpful in solving the problem.

**Comment by slopesweb** [comment]
@k-ivan Sorry. I messed up the question. I was messing with another lib and ended up confusing it. It's all working fine.

What I wanted was to activate the "focus" on the input when the modal was opened.

**Comment by k-ivan** [comment]
> @k-ivan Sorry. I messed up the question. I was messing with another lib and ended up confusing it. It's all working fine.
> 
> What I wanted was to activate the "focus" on the input when the modal was opened.

Ok )

**Comment by k-ivan** [comment]
> What I wanted was to activate the "focus" on the input when the modal was opened.

for example:
```js
modal.element.addEventListener('gmodal:open', function(evt) {
  modal.element.querySelector('input')?.focus()
})
```

**Comment by slopesweb** [comment]
@k-ivan Perfect. It Works very well. ;) 
![grlory offcanvas](https://i.imgur.com/PMt0NZd.png)
